---
networks:
  default:
    name: traefik
    driver: bridge
    attachable: true
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --api.debug=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=mediaboxlite.ibeep.com
      - --entrypoints.websecure.http.tls.domains[0].sans=*.mediaboxlite.ibeep.com
      - --entryPoints.ssh.address=:222
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesResolvers.letsencrypt.acme.email=letsencrypt@ibeep.com
      - --certificatesResolvers.letsencrypt.acme.storage=/certs/acme.json
      #- --certificatesResolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # staging
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=10
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers[0]=1.1.1.1:53
    ports:
      - 80:80
      - 8081:8080
      #- 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: HostRegexp(`^traefik\.mediaboxlite\..*$`)
      traefik.http.routers.traefik.entrypoints: web
      traefik.http.services.traefik.loadbalancer.server.port: 8080
  whoami:
    image: traefik/whoami
    container_name: simple-service
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: HostRegexp(`^mediaboxlite\..*$`)
      traefik.http.routers.whoami.entrypoints: web
