[[stack]]
name = "mediaboxlite-traefik"
tags = ["mediaboxlite-traefik"]
[stack.config]
server = "mediaboxlite"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
destroy_before_deploy = true
git_account = "b-"
repo = "b-/mediaboxlite-traefik"
reclone = true
file_paths = [
  "log-tail.compose.yaml",
  "logdy.compose.yaml",
  "logrotate.compose.yaml",
  "redis-kop.compose.yaml",
  "traefik.compose.yaml",
  "upnp.compose.yaml"
]
environment = """
CF_API_EMAIL = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__EMAIL]]
CF_DNS_API_TOKEN = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__CREDENTIAL]]
TRAEFIK_DOCKER_NETWORK=traefik
TRAEFIK_RULE_PREFIX=[[OP__KOMODO__TRAEFIK__RULE_PREFIX]]
TRAEFIK_RULE_SUFFIX=[[OP__KOMODO__TRAEFIK__RULE_SUFFIX]]
"""

##

[[resource_sync]]
name = "mediaboxlite-traefik"
tags = ["mediaboxlite-traefik"]
[resource_sync.config]
repo = "b-/mediaboxlite-traefik"
git_account = "b-"
resource_path = ["sync.toml"]
managed = true
delete = true
match_tags = ["mediaboxlite-traefik"]