[[stack]]
name = "traefik-internal"
tags = ["mediaboxlite-traefik"]
[stack.config]
server = "traefik-host-01"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "b-"
repo = "b-/mediaboxlite-traefik"
file_paths = [
  "log-tail.compose.yaml",
  "logdy.compose.yaml",
  "logrotate.compose.yaml",
  "redis-kop.compose.yaml",
  "traefik.compose.yaml",
  "upnp.compose.yaml",
  "ts-sidecars.compose.yaml"
]
ignore_services = ["logrotate"]
environment = """
CF_API_EMAIL = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__EMAIL]]
CF_DNS_API_TOKEN = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__CREDENTIAL]]
TRAEFIK_DOCKER_NETWORK=traefik
TRAEFIK_RULE_PREFIX=[[OP__KOMODO__TRAEFIK__RULE_PREFIX]]
TRAEFIK_RULE_SUFFIX=[[OP__KOMODO__TRAEFIK__RULE_SUFFIX]]
TS_AUTHKEY = [[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]?ephemeral=true
"""

##

[[resource_sync]]
name = "traefik-internal"
tags = ["mediaboxlite-traefik"]
[resource_sync.config]
repo = "b-/mediaboxlite-traefik"
git_account = "b-"
resource_path = ["sync.toml"]
managed = true
delete = true
match_tags = ["mediaboxlite-traefik"]