[[stack]]
name = "mediaboxlite-traefik"
tags = ["mediaboxlite-traefik"]
[stack.config]
server = "mediaboxlite"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "b-"
repo = "b-/mediaboxlite-traefik"
reclone = true
environment = """
CF_API_EMAIL = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__EMAIL]]
CF_DNS_API_TOKEN = [[OP__KOMODO__CLOUDFLARE_APIKEY_TRAEFIK__CREDENTIAL]]
"""

##

[[resource_sync]]
name = "mediabox-traefik"
tags = ["mediaboxlite-traefik"]
[resource_sync.config]
repo = "b-/mediaboxlite-traefik"
git_account = "b-"
resource_path = ["sync.toml"]
managed = true
delete = true
match_tags = ["mediaboxlite-traefik"]
