accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  # filters:
  #   statusCodes:
  #     - "200-299" # log successful http requests
  #     - "400-599" # log failed http requests
  # collect logs as in-memory buffer before writing into log file
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
        User-Agent: keep # log user agent strings
log:
  # format: json
  level: DEBUG
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
api:
  dashboard: true
  insecure: true
  debug: false
http:
  routers:
    idracRouter:
      rule: HostRegexp(`idrac\..*$`)
      service: idracService
    middlewares:
      - security-headers@file
      - rate-limit@file
  services:
    idracService:
      loadBalancer:
        servers:
          - url: "http://192.168.1.201"
providers:
  docker:
    exposedByDefault: false
  redis:
    endpoints:
      - traefik-internal-redis:6379
      - traefik-internal-redis.ts.shark-perch.net:6379
  file:
    directory: "/config/dynamic"
    watch: true
entryPoints:
  web:
    address: ":80"
    #asDefault: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    asDefault: true
    address: ":443"
    http:
      middlewares:
        - security-headers@file
        - rate-limit@file
      tls:
        certResolver: leresolver
        domains:
          - main: ibeep.com
            sans:
              - "ibeep.com"
              - "*.ibeep.com"
              - "*.traefik-internal-01.ibeep.com"
              - "*.traefik-internal-01.lan.ibeep.com"
              - "*.traefik-internal-01.ts.ibeep.com"
              - "*.traefik-internal-01.wan.ibeep.com"
              - "*.traefik-internal-01.home.ibeep.com"
              #- "*.mediaboxlite.ibeep.com"
              #- "*.mediaboxlite.lan.ibeep.com"
              #- "*.mediaboxlite.ts.ibeep.com"
              #- "*.mediaboxlite.wan.ibeep.com"
              #- "*.mediaboxlite.lan.ibeep.com"
              #- "*.mediaboxlite.home.ibeep.com"
  ssh:
    address: ":222"
certificatesResolvers:
  leresolver:
    acme:
      email: letsencrypt@ibeep.com
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 8.8.8.8:53
          - 1.1.1.1:53
serversTransport:
  insecureSkipVerify: true
experimental:
  plugins:
    cache:
      moduleName: "github.com/iamolegga/plugin-simplecache"
      version: "v0.3.0"
